trigger:
  - main
  - develop

steps:
  - script: |
      echo User-agent: \* > robots.txt
      echo Disallow: / >> robots.txt
    workingDirectory: public
    displayName: 'disable indexing via robots.txt for non-main builds'
    condition: ne(variables['Build.SourceBranchName'], 'main')

  - script: |
      docker login $(DOCKER_REGISTRY) -u $(DOCKER_USER) -p $(DOCKER_PASSWORD)
    displayName: 'Docker authorization'

  - script: |
      docker build --no-cache \
        --build-arg BUILD_ID=$(Build.BuildNumber) \
        -f preview/Dockerfile \
        -t $(DOCKER_REGISTRY)/$(REPOSITORY):$(Build.BuildNumber) .
    displayName: 'Build NextJS Preview Site Image'

  - script: |
      docker push $(DOCKER_REGISTRY)/$(REPOSITORY):$(Build.BuildNumber)
      docker tag $(DOCKER_REGISTRY)/$(REPOSITORY):$(Build.BuildNumber) $(DOCKER_REGISTRY)/$(REPOSITORY):$(Build.SourceBranchName)
      docker push $(DOCKER_REGISTRY)/$(REPOSITORY):$(Build.SourceBranchName)
    displayName: 'Push NextJS Preview Site Images'
