trigger:
  - main
  - develop

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    - name: leadCmsUrl
      value: '$(LEADCMS_URL)'
    - name: leadCmsApiKey
      value: '$(LEADCMS_API_KEY)'
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
    - name: leadCmsUrl
      value: '$(DEV_LEADCMS_URL)'
    - name: leadCmsApiKey
      value: '$(DEV_LEADCMS_API_KEY)'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '24.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g pnpm
    displayName: 'Install pnpm'

  - script: |
      echo User-agent: \* > robots.txt
      echo Disallow: / >> robots.txt
    workingDirectory: public
    displayName: 'disable indexing via robots.txt for non-main builds'
    condition: ne(variables['Build.SourceBranchName'], 'main')

  - script: |
      pnpm install
    displayName: 'pnpm install'

  - script: |
      pnpm run build
    displayName: 'pnpm run build'
    env:
      NEXT_PUBLIC_LEADCMS_URL: '$(leadCmsUrl)'
      LEADCMS_API_KEY: '$(leadCmsApiKey)'

  - script: |
      docker login $(DOCKER_REGISTRY) -u $(DOCKER_USER) -p $(DOCKER_PASSWORD)
    displayName: 'Docker authorization'

  - script: |
      docker build --no-cache \
        --build-arg BUILD_ID=$(Build.BuildNumber) \
        --build-arg NEXT_PUBLIC_LEADCMS_URL=$(leadCmsUrl) \
        --build-arg LEADCMS_API_KEY=$(leadCmsApiKey) \
        -f Dockerfile \
        -t $(DOCKER_REGISTRY)/$(REPOSITORY):$(Build.BuildNumber) .
    displayName: 'Build NextJS Site Image'

  - script: |
      docker push $(DOCKER_REGISTRY)/$(REPOSITORY):$(Build.BuildNumber)
      docker tag $(DOCKER_REGISTRY)/$(REPOSITORY):$(Build.BuildNumber) $(DOCKER_REGISTRY)/$(REPOSITORY):$(Build.SourceBranchName)
      docker push $(DOCKER_REGISTRY)/$(REPOSITORY):$(Build.SourceBranchName)
    displayName: 'Push NextJS Site Images'
